import { Product } from './models.js';

export const CATEGORIES = [
  { key: 'birthday', title: 'Special Birthday Items', blurb: 'Make their birthday unforgettable (they will try to forget it).' },
  { key: 'food', title: 'Food Items', blurb: 'Delicious, nutritious and 100% inedible.' },
  { key: 'travel', title: 'Travel Items', blurb: 'For when the auto-wala says no.' },
  { key: 'summer', title: 'Summer Special', blurb: 'Beat the heat. Permanently.' },
];

const r = (user, stars, text) => ({ user, stars, text });

const PRODUCTS = [
  { slug: 'cow-dung-cake', name: 'Cow Dung Cake', category: 'birthday', emoji: '💩🎂', price: 99, mrp: 49,
    tagline: 'Organic. Handmade. Hand-made. Please wash your hands.',
    description: 'Freshly baked under the sun by Gauri the cow. Gluten-free, sugar-free, taste-free. Candles sold separately (they will not stay lit).',
    reviews: [r('Pinku', 5, 'Gave it to my boss. I now work from home permanently.'), r('Ramesh', 1, 'Was expecting chocolate. It was not chocolate.')] },
  { slug: 'birthday-belt', name: 'Birthday Belt (Patta)', category: 'birthday', emoji: '🪢🎉', price: 249, mrp: 199,
    tagline: 'For the traditional birthday bumps.',
    description: 'Premium genuine-ish leather. Approved by every hostel in India. Comes with a free "Happy Birthday" sound effect every time it is used.',
    reviews: [r('Hostel Room 204', 5, 'Birthday boy still cannot sit. 10/10.'), r('Birthday Boy', 1, 'Why does this exist.')] },
  { slug: 'cake-for-face', name: 'Cake for Face', category: 'birthday', emoji: '🎂😵', price: 199, mrp: 150,
    tagline: 'Not for eating. Strictly for face application.',
    description: 'Aerodynamic design for maximum splash radius. Includes 0 forks, because why would you eat it?',
    reviews: [r('Sonu', 5, 'Smashed it on my friend. Friendship also smashed.'), r('Dermatologist', 3, 'Surprisingly good for the skin.')] },

  { slug: 'chappal', name: 'Chappal (Crunchy)', category: 'food', emoji: '🩴', price: 149, mrp: 99,
    tagline: 'Mummy\'s favourite. Fibre-rich.',
    description: 'Rubber flavoured, best served flying. Pairs well with bad report cards. Single piece only, the other one is with Mummy.',
    reviews: [r('Every Indian Kid', 5, 'Tasted it many times, never ordered it.'), r('Mummy', 5, 'Accurate up to 30 metres.')] },
  { slug: 'shoes', name: 'Shoes (Spicy)', category: 'food', emoji: '👟🌶️', price: 499, mrp: 399,
    tagline: 'Mildly spicy, extremely chewy.',
    description: 'Laces are noodles (they are not). Previously worn by a marathon runner for extra flavour.',
    reviews: [r('Dog', 5, 'Ate both. Delicious.'), r('Dog\'s owner', 1, 'My dog ate both.')] },
  { slug: 'belan', name: 'Belan', category: 'food', emoji: '🪵', price: 199, mrp: 149,
    tagline: 'Makes rotis. Also makes husbands come home on time.',
    description: 'Solid sheesham wood. 100% roti-compatible, 200% husband-compatible.',
    reviews: [r('Wife', 5, 'Multi-purpose. Love it.'), r('Husband', 1, 'Please send help.')] },
  { slug: 'kalchhul', name: 'Kalchhul (Ladle)', category: 'food', emoji: '🥄🔥', price: 129, mrp: 89,
    tagline: 'Now in "Freshly Heated" edition.',
    description: 'Stirs dal. Stirs drama. Comes pre-heated so you can feel the warmth of a mother\'s love.',
    reviews: [r('Chef', 4, 'Holds a lot of dal.'), r('Teenager', 1, 'Mom found my report card.')] },
  { slug: 'big-spoons', name: 'Big Spoons', category: 'food', emoji: '🥄🥄🥄', price: 179, mrp: 120,
    tagline: 'Spoons for people with big dreams (and big mouths).',
    description: 'Each spoon is 1.5 metres long. Feeding yourself is impossible, so feed each other. Builds teamwork.',
    reviews: [r('Wedding Caterer', 5, 'Served 400 guests with one scoop.'), r('Anonymous', 2, 'Got stuck in the doorway.')] },
  { slug: 'cheese-sharam', name: 'Sharam Cheese', category: 'food', emoji: '🧀😳', price: 299, mrp: 250,
    tagline: 'Kuch toh Sharam karo. Now available in blocks.',
    description: 'Aged 12 years in the same room as your embarrassing childhood photos. If you have no sharam, buy some here.',
    reviews: [r('Neighbour Aunty', 5, 'Finally my son has some Sharam.'), r('Son', 1, 'Sharam aa rahi hai.')] },

  { slug: 'private-jet', name: 'Private Jet', category: 'travel', emoji: '🛩️', price: 4999999, mrp: 3500000,
    tagline: 'Free delivery*. *Engine sold separately.',
    description: 'Seats 12. Fuel not included. Pilot not included. Wings not included. Basically a very expensive bench.',
    reviews: [r('Elon M.', 4, 'Smaller than expected.'), r('Raju', 5, 'Parked it in the society. Secretary is angry.')] },
  { slug: 'chartered-plane', name: 'Chartered Plane', category: 'travel', emoji: '🛫', price: 5999999, mrp: 4500000,
    tagline: 'Charter it. Then explain it to your CA.',
    description: 'Fly anywhere you want, as long as it is within 2 km of your house. Snacks cost extra (₹4,000 per peanut).',
    reviews: [r('CA Sharma', 1, 'Client is now in jail.'), r('Client', 5, 'Worth it.')] },
  { slug: 'boeing-777', name: 'Boeing 777', category: 'travel', emoji: '✈️', price: 7777777, mrp: 6000000,
    tagline: 'EMI available: ₹1/month for 77,77,777 months.',
    description: 'Lightly used. Some doors may come off during flight (feature, not a bug). Comes with 396 seats and 0 legroom.',
    reviews: [r('Frequent Flyer', 2, 'Door flew off. Got free air conditioning.')] },
  { slug: 'airbus', name: 'Airbus (A Bus with Wings)', category: 'travel', emoji: '🚌🪽', price: 8999999, mrp: 7000000,
    tagline: 'It is literally a bus. With wings glued on.',
    description: 'Runs on diesel and prayers. Conductor will still ask for change. Stops at every village for chai.',
    reviews: [r('Conductor', 5, 'Chhutta do.'), r('Passenger', 3, 'Never took off. Very punctual though.')] },
  { slug: 'helicopter', name: 'Helicopter', category: 'travel', emoji: '🚁', price: 2499999, mrp: 2000000,
    tagline: 'Comes with a free "Helicopter Shot" tutorial.',
    description: 'Great for wedding entries. Blades rotate at 3 rpm for safety. Takes 4 hours to rise one metre.',
    reviews: [r('Dulha', 5, 'Grand entry. Arrived after the wedding was over.')] },

  { slug: 'mortuary-room', name: 'Mortuary Room', category: 'summer', emoji: '⚰️❄️', price: 999, mrp: 799,
    tagline: 'The coolest room in town. Literally.',
    description: 'Maintains a crisp -4°C all summer. Very quiet neighbours. Check-in is easy, check-out is complicated.',
    reviews: [r('Mr. Cold', 5, 'Most peaceful sleep of my life. Still sleeping.'), r('Electricity Board', 5, 'Thank you for your business.')] },
  { slug: 'fridge', name: 'Fridge (Walk-in Bedroom Edition)', category: 'summer', emoji: '🧊🛏️', price: 1499, mrp: 1199,
    tagline: 'Who needs AC when you can live in the fridge?',
    description: 'Fits one adult, two bottles of water and Mummy\'s leftover sabzi in a Bournvita jar. Light turns off when you close the door (we checked).',
    reviews: [r('Bhaiya', 5, 'Moved in last May. Not coming out.'), r('Mummy', 1, 'Where do I keep the doodh now?')] },

  { slug: 'birthday-eggs', name: 'Birthday Eggs (For Head Use Only)', category: 'birthday', emoji: '🥚🤕', price: 89, mrp: 60,
    tagline: 'A dozen reasons to never tell anyone your birthday.',
    description: 'Hand-picked eggs, aged 3 weeks for maximum aroma. Comes with a free shampoo sachet (expired).',
    reviews: [r('Birthday Boy', 1, 'Still smell like an omelette.'), r('Hostel Gang', 5, 'Ran out by 12:01 AM. Ordering 50 more.')] },
  { slug: 'trick-candles', name: 'Candles That Never Die', category: 'birthday', emoji: '🕯️😤', price: 79, mrp: 49,
    tagline: 'Blow all you want. They will outlive you.',
    description: 'Self-relighting candles powered by spite. Fire brigade number printed on the box for your convenience.',
    reviews: [r('Grandpa (80)', 1, 'Blew for 40 minutes. Now on oxygen.'), r('Fire Brigade', 4, 'Good for business.')] },
  { slug: 'gift-box-air', name: 'Gift Box of Fresh Air', category: 'birthday', emoji: '🎁💨', price: 149, mrp: 99,
    tagline: 'Contains 100% organic nothing.',
    description: 'Premium Himalayan air, carefully packed by an uncle in Noida. Open slowly to avoid disappointment.',
    reviews: [r('Gift Receiver', 2, 'It was empty. Like my bank account.'), r('Gift Giver', 5, 'Saved so much money.')] },
  { slug: 'dimag', name: 'Dimag (Brain, Slightly Used)', category: 'birthday', emoji: '🧠🗑️', price: 99, mrp: 69,
    tagline: 'For that one friend who clearly never had one.',
    description: 'Pre-owned brain, only used during exams. Some memories of 2012 still inside. Not compatible with WhatsApp University.',
    reviews: [r('Best Friend', 5, 'Gifted it to my roommate. He still uses it to store memes.'), r('Roommate', 1, 'Came without a manual. Still confused.')] },
  { slug: 'akal', name: 'Akal (Common Sense)', category: 'birthday', emoji: '💡', price: 129, mrp: 89,
    tagline: 'So rare that we only have 1 piece left. Since 1947.',
    description: 'One bottle of common sense. Apply twice a day before speaking. Warning: side effects include sudden silence in family groups.',
    reviews: [r('Papa', 5, 'Bought 10 for my son. Still not enough.'), r('Son', 1, 'Did not work. Asked Papa for refund, got chappal.')] },
  { slug: 'sabr', name: 'Sabr (Patience)', category: 'birthday', emoji: '⏳😤', price: 149, mrp: 99,
    tagline: 'Delivery in 6–8 years. Have patience.',
    description: 'Premium patience, perfect for people who honk at red lights. Comes in a box that takes 45 minutes to open.',
    reviews: [r('Delhi Driver', 1, 'Waited 2 seconds, then gave up.'), r('Customer Care', 5, 'Our whole team runs on this.')] },
  { slug: 'izzat', name: 'Izzat (Respect)', category: 'birthday', emoji: '👑📉', price: 199, mrp: 149,
    tagline: 'Finally, some respect. Batteries not included.',
    description: 'Imported respect for people who get none at home. Disappears the moment you ask for pocket money.',
    reviews: [r('Middle Child', 5, 'First time anyone noticed me.'), r('Sharmaji ka Beta', 3, 'Already had plenty. Gifted to cousin.')] },
  { slug: 'neend', name: 'Neend (8 Hours of Sleep)', category: 'birthday', emoji: '😴💤💤', price: 79, mrp: 49,
    tagline: 'For engineering students and new parents only.',
    description: 'A fresh pack of 8 uninterrupted hours. Expires at 3 AM when you remember something embarrassing from class 6.',
    reviews: [r('Engineering Student', 5, 'Heard about it in legends.'), r('New Mom', 1, 'Opened it. Baby woke up. Pack expired.')] },
  { slug: 'popped-balloons', name: 'Pre-Popped Balloons (Pack of 50)', category: 'birthday', emoji: '🎈💥', price: 59, mrp: 30,
    tagline: 'We popped them so you don\'t have to.',
    description: 'Zero scary bangs at the party. Just sad pieces of rubber lying around, like your dreams.',
    reviews: [r('Decorator', 3, 'Party looked like a crime scene.')] },

  { slug: 'crispy-tawa', name: 'Tawa (Extra Crispy)', category: 'food', emoji: '🍳🔥', price: 199, mrp: 149,
    tagline: 'Iron-rich. Literally 100% iron.',
    description: 'Pre-seasoned with 15 years of burnt rotis. Recommended with a side of dental insurance.',
    reviews: [r('Dentist', 5, 'Bought a new car thanks to this.'), r('Customer', 1, 'Teeth are now on the tawa.')] },
  { slug: 'pressure-cooker', name: 'Pressure Cooker Whistle Soup', category: 'food', emoji: '🍲📢', price: 249, mrp: 199,
    tagline: 'Tastes like 3 whistles and your neighbours\' complaints.',
    description: 'A hot bowl of steam served straight from the cooker. Hearing loss included at no extra cost.',
    reviews: [r('Neighbour', 1, 'Woke up the whole colony at 6 AM.'), r('Mummy', 5, 'Count the whistles, beta.')] },
  { slug: 'brick-biscuit', name: 'Brick Biscuit (Parle-Bhai)', category: 'food', emoji: '🧱🍪', price: 99, mrp: 69,
    tagline: 'Dip it in chai for 7–10 business years.',
    description: 'High-fibre, high-cement snack. Perfect for building a house or building character.',
    reviews: [r('Contractor', 5, 'Built a wall with two packets.'), r('Chai Lover', 1, 'My cup broke.')] },
  { slug: 'soap-paneer', name: 'Paneer (Soap Flavour)', category: 'food', emoji: '🧼🧀', price: 179, mrp: 129,
    tagline: 'Clean from the inside out.',
    description: 'Looks like paneer. Foams like soap. Your shahi paneer will finally smell fresh.',
    reviews: [r('Uncle Ji', 2, 'Burped bubbles for 3 days.'), r('Aunty', 5, 'Kitchen smells like lavender now.')] },

  { slug: 'bullock-cart', name: 'Bullock Cart (Business Class)', category: 'travel', emoji: '🐂🛞', price: 2199999, mrp: 1500000,
    tagline: 'Zero emissions. Some emissions. Okay, a lot of emissions.',
    description: 'Fully reclining hay seats, organic engine (2 BHP — Bull Horse Power). In-flight meal: the engine\'s fodder.',
    reviews: [r('Pilot (Ramu Kaka)', 5, 'Never once crashed. Never once exceeded 4 km/h.')] },
  { slug: 'hot-air-balloon', name: 'Hot Air Balloon (Powered by Uncle Gossip)', category: 'travel', emoji: '🎈🔥', price: 3499999, mrp: 2500000,
    tagline: 'Fuelled entirely by hot air from family WhatsApp groups.',
    description: 'Rises whenever Sharma Uncle starts talking politics. Lands only when he runs out of forwards.',
    reviews: [r('Passenger', 4, 'Floated for 9 hours. Uncle still talking.')] },
  { slug: 'submarine', name: 'Submarine (Screen Door Edition)', category: 'travel', emoji: '🛥️🪟', price: 6999999, mrp: 5000000,
    tagline: 'Comes with a screen door to keep mosquitoes out.',
    description: 'Dives to a depth of 0.5 metres. Windows open for ventilation. Snorkel sold separately.',
    reviews: [r('Captain', 1, 'Sank in the parking lot.'), r('Fish', 5, 'Lovely new home.')] },
  { slug: 'rocket', name: 'Rocket (One-Way Ticket)', category: 'travel', emoji: '🚀👋', price: 9499999, mrp: 8000000,
    tagline: 'Return ticket available on request (request denied).',
    description: 'Perfect for in-laws, exes and people who say "I don\'t watch cricket". Seat belt is optional. So is landing.',
    reviews: [r('Saas', 1, 'Bahu gifted me this. Now in orbit.'), r('Bahu', 5, 'Best purchase ever.')] },

  { slug: 'single-ice-cube', name: 'Premium Ice Cube (Single)', category: 'summer', emoji: '🧊💎', price: 199, mrp: 149,
    tagline: 'Delivered by bicycle across Rajasthan.',
    description: 'Hand-frozen artisan ice cube. Arrives as a premium water droplet. Packaging may be wet.',
    reviews: [r('Jaipur Customer', 1, 'Received a damp box.'), r('Delivery Boy', 3, 'Pedalled very fast. Still lost.')] },
  { slug: 'desert-cooler', name: 'Desert Cooler (Heater Mode Stuck)', category: 'summer', emoji: '🌬️🔥', price: 999, mrp: 799,
    tagline: 'Turns your room into an actual desert.',
    description: 'Blows hot air with 3 speeds: Hot, Hotter and Sahara. Comes with free sand and a camel sticker.',
    reviews: [r('Camel', 5, 'Feels like home.'), r('Customer', 1, 'Got a tan indoors.')] },
  { slug: 'igloo', name: 'Igloo (1BHK, Delhi Edition)', category: 'summer', emoji: '🏠❄️', price: 1299, mrp: 999,
    tagline: 'Delivered as a 1BHK. Arrives as a swimming pool.',
    description: 'Prime location, ice-cold vibes. Possession date: never, because it melts on the way. Broker fee 2 months.',
    reviews: [r('Delhi Tenant', 2, 'Melted before the landlord asked for rent. Worth it.')] },
  { slug: 'hand-fan', name: 'Hand Fan (Battery Not Included)', category: 'summer', emoji: '🪭🔋', price: 149, mrp: 99,
    tagline: 'Requires 2 AA batteries and 1 strong wrist.',
    description: 'Manual fan with no battery slot. Customer care will still ask you to check the batteries.',
    reviews: [r('Customer Care', 5, 'Have you tried turning it off and on?'), r('Customer', 1, 'Wrist is now bigger than my face.')] },
];

export async function seed() {
  for (const p of PRODUCTS) {
    await Product.updateOne({ slug: p.slug }, { $set: p }, { upsert: true });
  }
}
